apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
      - name: as
        image: us.icr.io/dnsapp/as:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 53533
          protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: as-service
spec:
  type: NodePort
  selector:
    app: as
  ports:
  - port: 53533
    protocol: UDP
    targetPort: 53533
    nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
      - name: fs
        image: us.icr.io/dnsapp/fs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: fs-service
spec:
  type: NodePort
  selector:
    app: fs
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us
  template:
    metadata:
      labels:
        app: us
    spec:
      containers:
      - name: us
        image: us.icr.io/dnsapp/us:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: us-service
spec:
  type: NodePort
  selector:
    app: us
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30003
